# Yaml file tha define github action from bast project

name: bast-wrap-up

on: 
  push:
    branches:
      - 'ideas/wrap-up'
  pull_request:
    types: [opened]
    branches:
      - master

jobs:
  make:
    name: Make build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [12.x]

    steps:
      # Setup node js
      - name: Setup node {{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          nodes-version: matrix.node
          scope: '@dual-lab'
      # chekout step
      - name: Checkout repository
        uses: actions/checkout@v2
      # setup yarn cache  
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
         path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
         key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
         restore-keys: |
           ${{ runner.os }}-yarn-
      # Install dep step
      - name: Install node dependecies
        run: yarn install
      # Build step
      - name: Make build
        run: yarn run build
      # Test step
      - name: Make test
        run: yarn run test
     